// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtvvyopjzdmbnpgwhkbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0dnZ5b3BqemRtYm5wZ3doa2JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMTQ3NzgsImV4cCI6MjA2ODY5MDc3OH0.4x3pzDpE18cCMKDMpKZpaUKSWzpwhC43z_R-TKNoAII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});